version: '2'

services:

  db:
    image: postgres:12.8
    environment:
      - POSTGRES_PASSWORD=example
      - PGDATA=/var/lib/postgresql/data/nuremberg
    volumes:
      # NAMED VOLUMES
      # If the volume contains a database (a subdirectory named mysql)
      # when you start the container, it will be left untouched and unaffected
      # by changes to environment variables like $MYSQL_ROOT_PASSWORD.
      - db_data:/var/lib/postgresql/data:delegated
    ports:
      - "127.0.0.1:54320:5432"
  solr:
    build:
      context: ./
      dockerfile: solr.dockerfile
    image: nuremberg-solr:0.3
    ports:
      - "127.0.0.1:8983:8983"
    volumes:
      # NAMED VOLUMES
      - solr_data:/var/solr
  web:
    build:
      context: ./
      dockerfile: web.dockerfile
    image: nuremberg:0.15
    tty: true
    command: bash
    volumes:
      # BIND MOUNTS
      - ./:/nuremberg
    environment:
      # let Django load Docker-specific settings conditionally
      - DOCKERIZED=True
    ports:
      - "127.0.0.1:8000:8000"
    depends_on:
      - db
      - solr
  selenium:
    image: selenium/standalone-chrome:3.141.59
    ports:
      - "4444:4444"
    environment:
      PORT: 4444
      SCREEN_WIDTH: 1200
      SCREEN_HEIGHT: 900
      SCREEN_DEPTH: 24

volumes:
  db_data:
  solr_data:
